services:
  - type: web
    name: irritool
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: FAOSTAT_USERNAME
        sync: false
      - key: FAOSTAT_PASSWORD
        sync: false
